# configuration for "master" branch
-
  branches:
    only:
      - master

  version: 1.1.{build}

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  platform: Any CPU

  configuration:
    - Release

  environment:
    TreatWarningsAsErrors: false

  skip_tags: true

  cache:
    - packages -> **\packages.config

  before_build:
    - nuget restore SS.Login.sln

  build:
    project: SS.Login.sln       # path to Visual Studio solution or project
    publish_nuget: true

  artifacts:
    - path: '*.nupkg'

  deploy:
    provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: cKpWZvlfFA7EfagAXc/mZfTGHXxfoKNOYTQd6v4ImalbNV1mtNR55M2HMJJ4jCAo
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/

# configuration for "dev" branch
-
  branches:
    only:
      - dev

  version: 1.1.{build}-beta

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  platform: Any CPU

  configuration:
    - Release

  environment:
    TreatWarningsAsErrors: false

  skip_tags: true

  cache:
    - packages -> **\packages.config

  before_build:
    - nuget restore SS.Login.sln

  build:
    project: SS.Login.sln       # path to Visual Studio solution or project
    publish_nuget: true

  artifacts:
    - path: '**/*.nupkg'

  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/siteserver/api/v2/package                 # remove to push to NuGet.org
      api_key:
        secure: i9vISdFyCeWbRUQw+jhcF748i4oWdeatGBrx+dJ07SDTpt7Hsk9YCRp/ha3ZXfZF
      skip_symbols: false
      symbol_server:           # remove to push symbols to SymbolSource.org
      artifact: /.*\.nupkg/

  notifications:
    - provider: Webhook
      url: http://api.siteserver.cn/v1.1/packages/SS.Login?isNightly=true
      headers:
        X-SiteServer-ApiKey:
          secure: BgJi7I52wZsaeoldjE1txzqjNWIqDwUUYzH5VFoVrZUW2NlSocZlSl1uXKE2PQut
      on_build_success: true